# generic packages and tmux
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git-core jq
  - sudo apt-get install -y python-software-properties software-properties-common
  - sudo apt-get install -y libevent-dev libncurses-dev
  - git clone https://github.com/tmux/tmux.git
  - cd tmux
  - git checkout 3.2a
  - sh autogen.sh
  - ./configure && make && sudo make install

install:
  - true

script: ./run_tests
