# Common AWK helpers for tmux-resurrect restore.
# Save files are newline-delimited JSON objects generated by save.sh.  These
# helpers intentionally support the flat scalar objects used by the v2 format;
# they are not a general-purpose JSON parser.

function init_json_helpers(    i) {
	for (i = 1; i < 256; i++) {
		chr[i] = sprintf("%c", i)
		ord[chr[i]] = i
	}
}

BEGIN {
	init_json_helpers()
}

function hex_value(hex,    i, c, n, digit) {
	n = 0
	for (i = 1; i <= length(hex); i++) {
		c = substr(hex, i, 1)
		if (c >= "0" && c <= "9") digit = c + 0
		else if (c >= "a" && c <= "f") digit = index("abcdef", c) + 9
		else if (c >= "A" && c <= "F") digit = index("ABCDEF", c) + 9
		else return -1
		n = n * 16 + digit
	}
	return n
}

function has_json_key(line, key) {
	return index(line, "\"" key "\":") > 0
}

function jv(line, key,    pat, val, i, c, result, j, e, hex, code) {
	pat = "\"" key "\":"
	i = index(line, pat)
	if (i == 0) return ""
	val = substr(line, i + length(pat))
	if (substr(val, 1, 1) == "\"") {
		val = substr(val, 2)
		result = ""
		for (j = 1; j <= length(val); j++) {
			c = substr(val, j, 1)
			if (c == "\\" && j < length(val)) {
				j++
				e = substr(val, j, 1)
				if (e == "\"" || e == "\\" || e == "/") result = result e
				else if (e == "b") result = result chr[8]
				else if (e == "f") result = result chr[12]
				else if (e == "n") result = result chr[10]
				else if (e == "r") result = result chr[13]
				else if (e == "t") result = result chr[9]
				else if (e == "u" && j + 4 <= length(val)) {
					hex = substr(val, j + 1, 4)
					code = hex_value(hex)
					if (code >= 0) {
						if (code <= 255) result = result chr[code]
						else result = result "\\u" hex
						j += 4
					} else {
						result = result e
					}
				} else {
					result = result e
				}
			} else if (c == "\"") {
				break
			} else {
				result = result c
			}
		}
		return result
	} else {
		sub(/[^0-9-].*/, "", val)
		return val
	}
}

# Quote a string for tmux source-file (double-quote syntax).
function tq(s,    out, i, c) {
	out = ""
	for (i = 1; i <= length(s); i++) {
		c = substr(s, i, 1)
		if (c == "\\") out = out "\\\\"
		else if (c == "\"") out = out "\\\""
		else if (c == "$") out = out "\\$"
		else if (c == "#") out = out "\\#"
		else if (c == chr[8]) out = out "\\010"
		else if (c == chr[9]) out = out "\\t"
		else if (c == chr[10]) out = out "\\n"
		else if (c == chr[12]) out = out "\\014"
		else if (c == chr[13]) out = out "\\r"
		else if ((c in ord) && ord[c] < 32) out = out sprintf("\\%03o", ord[c])
		else out = out c
	}
	return "\"" out "\""
}

function is_int(s) {
	return s ~ /^-?[0-9]+$/
}

function is_nonnegative_int(s) {
	return s ~ /^[0-9]+$/
}

function is_bool_number(s) {
	return s == "0" || s == "1"
}
